import { Injectable, Logger, Inject } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createWorker } from 'tesseract.js';
import { ExtractionResultBlock } from './pdf-text.extractor';

@Injectable()
export class OcrExtractor {
  private readonly logger = new Logger(OcrExtractor.name);
  private readonly tesseractLang: string;
  private readonly minConfidence: number;

  constructor(private configService: ConfigService) {
    this.tesseractLang = this.configService.get<string>('ocr.tesseractLang') || 'jpn';
    this.minConfidence = this.configService.get<number>('ocr.minConfidence') || 0.6;
  }

  // Assuming `imagePaths` was pre-generated by converting PDF pages to images
  async extract(imagePaths: string[]): Promise<ExtractionResultBlock[]> {
    this.logger.debug(`Running OCR on ${imagePaths.length} pages`);
    const blocks: ExtractionResultBlock[] = [];

    const worker = await createWorker(this.tesseractLang);

    try {
      for (let i = 0; i < imagePaths.length; i++) {
        const pageNum = i + 1;
        const result = await worker.recognize(imagePaths[i]);

        // Break down by paragraphs or words depending on structural needs
        result.data.paragraphs.forEach(paragraph => {
          if (paragraph.confidence / 100 >= this.minConfidence) {
            blocks.push({
              type: 'text',
              text: paragraph.text.trim(),
              confidence: paragraph.confidence / 100,
              page: pageNum,
              bbox: {
                x: paragraph.bbox.x0,
                y: paragraph.bbox.y0,
                width: paragraph.bbox.x1 - paragraph.bbox.x0,
                height: paragraph.bbox.y1 - paragraph.bbox.y0
              }
            });
          }
        });
      }
    } finally {
      await worker.terminate();
    }

    return blocks;
  }
}
