export enum DocumentType {
  INVOICE = 'INVOICE',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  PURCHASE = 'PURCHASE',
  BILLING = 'BILLING',
  RECEIPT = 'RECEIPT',
  PACKING_LIST = 'PACKING_LIST',
  AUCTION_SHEET = 'AUCTION_SHEET',
  MIXED = 'MIXED',
  UNKNOWN = 'UNKNOWN',
}
